name: coleitra Bug Report
description: File a bug report for coleitra
title: "[Bug]: "
labels: ["bug"]
assignees:
  - 5balls
body:
  - type: markdown
    attributes:
      value: |
        # Thank you!

        Thank you for considering contributing to coleitra! To make the most of your and our time, we need some information from you. **You can find the following fields in the about screen in the coleitra program.**
  - type: dropdown
    attributes:
      label: coleitra version
      description: What version of coleitra are you running?
      multiple: false
      options:
        - 0.1
        - unreleased
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: What operating system are you using? (for example Android 9, Debian Linux 11, Windows 11, ...)
    validations:
      required: true
  - type: input
    attributes:
      label: Git commit
      description: Filling out this value (maybe copying directly from the about screen of the program) can be very helpful to reproduce the bug.
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this coleiras's [Code of Conduct](https://github.com/5balls/coleitra/blob/master/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for contributing to coleitra!"
