name: Create developer documentation for coleitra

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image to create the documentation
      run: DOCKER_BUILDKIT=1 docker build -f build/dockerfiles/coleitra_doc.Dockerfile -t coleitra_doc:$(date +%s) --output . .
    - name: Release documentation
      uses: softprops/action-gh-release@v1
      with:
        files: coleitra.pdf
